config/routes.rb
Rails.application.routes.draw do
  resources :comments

  root 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    comment = Comment.create!(comment_params)
    comment.images.attach(params[:comment][:images])
    redirect_to comment
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:nameL, :email, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.slim
.comment-layout
  nav aria-label='breadcrumb'
    ol class='breadcrumb'
      li class='breadcrumb-item'
        = link_to 'Home', root_path
      li class='breadcrumb-item active'
      | Comment

  = form_with model: @comment, data: { form: 'direct-uploads', ui: 'buri-uploads' }, local: true do |form|
    .form-group
      = form.label(:content)
      .col-sm-8
        = form.text_area :content, class: 'form-control', rows: '3', placeholder: 'Write your comment...'
    .form-group
      = form.label(:images)
      .col-sm-12
        = form.file_field :images, multiple: true, direct_upload: true, class: 'form-control-file'
    = form.submit class: 'btn btn-primary btn-block'

app/views/comments/show.html.slim
.comment-layout
  nav aria-label='breadcrumb'
    ol class='breadcrumb'
      li class='breadcrumb-item'
        = link_to 'Home', root_path
      li class='breadcrumb-item'
        = link_to 'Comment', new_comment_path
      li class='breadcrumb-item active'
      | Gallery

  .card-columns
    - @comment.images.each do |image|
      .card
        = image_tag image.variant(resize: '200x200'), class: 'card-img-top'
        .card-body
          p.card-text
            = @comment.content
          = link_to 'Download', rails_blob_path(image, disposition: 'attachment'), class: 'btn btn-primary'

app/views/dashboard/index.html.slim
.dashboard-layout
  = link_to 'New Comment', new_comment_path,
          class: 'btn btn-secondary btn-lg',
          role: 'button',
          aria: { pressed: 'true' }

app/views/layouts/application.html.slim
doctype html
html lang="en" class='layout-default'
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'
    meta name='viewport' content='width=device-width, initial-scale=1'

    title= content_for?(:title) ? yield(:title) : 'Filestack Like with Rails Active Storage'
    = csrf_meta_tags
    = stylesheet_link_tag 'application', :media => 'all', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js'
  body
    .container
      .row
        .offset-lg-2.col-lg-8
          = yield

    = javascript_include_tag 'application'

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nameL %>
    <%= form.text_field :nameL %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.filestack_field :picture, 'Upload Your Avatar' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Namel</th>
      <th>Email</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.nameL %></td>
        <td><%= user.email %></td>
        <td><%= user.picture %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Namel:</strong>
  <%= @user.nameL %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Picture:</strong>
  <%= filestack_image @user.picture, transform: filestack_transform.resize(width: 100, height: 100) %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>